from setuptools import setup, find_packages

setup(
    name="ai-influencer",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "google-auth-oauthlib>=1.0.0",
        "google-auth-httplib2>=0.1.0",
        "google-api-python-client>=2.0.0",
        "google-cloud-aiplatform>=1.36.0",
        "google-cloud-core>=2.3.3",
        "google-cloud-storage>=2.10.0",
        "google-cloud-logging>=3.5.0",
        "python-dotenv>=0.19.0",
        "beautifulsoup4>=4.9.3",
        "playwright>=1.40.0",
        "openai>=1.0.0",
        "pandas>=2.0.0",
        "newspaper3k>=0.2.8",
        "requests>=2.26.0",
        "feedparser>=6.0.0",
        "flask>=2.0.0",
        "fastapi>=0.68.0",
        "uvicorn>=0.15.0",
        "langgraph>=0.0.15",
        "langchain>=0.1.0",
        "langchain-openai>=0.0.2",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "pytest-asyncio>=0.21.0",
        ],
    },
    python_requires=">=3.8",
    author="Your Name",
    author_email="your.email@example.com",
    description="AI Influencer - Social Media Trend Analysis Tool",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/ai-influencer",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
) 