from apify_client import ApifyClient

client = ApifyClient("apify_token_here")
        
# Get search queries from context

video_data = []

query = "machine learning"
run_input = {
    "downloadSubtitles": False,
    "hasCC": False,
    "hasLocation": False,
    "hasSubtitles": False,
    "is360": False,
    "is3D": False,
    "is4K": False,
    "isBought": False,
    "isHD": False,
    "isHDR": False,
    "isLive": False,
    "isVR180": False,
    "maxResultStreams": 0,
    "maxResults": 10,
    "maxResultsShorts": 0,
    "preferAutoGeneratedSubtitles": False,
    "saveSubsToKVS": False,
    "searchQueries": [
        query
    ]
}

run = client.actor("streamers/youtube-scraper").call(run_input=run_input)

# Get the results
for item in client.dataset(run["defaultDatasetId"]).iterate_items():
    video_data.append({
        'title': item.get('title'),
        'description': item.get('description'),
        'url': item.get('url'),
        'views': item.get('viewCount'),
        'likes': item.get('likeCount'),
        'uploadDate': item.get('uploadDate')
    })

print(video_data)